eval.batch_size: 2
eval.cutoff_len: 1024
eval.dataset:
- identity
eval.dataset_dir: data
eval.max_new_tokens: 512
eval.max_samples: '100000'
eval.output_dir: eval_2026-03-16-18-18-10
eval.predict: true
eval.temperature: 0.95
eval.top_p: 0.7
top.booster: auto
top.checkpoint_path:
- train_2026-03-16-18-18-10
top.finetuning_type: lora
top.model_name: Qwen2.5-0.5B
top.quantization_bit: none
top.quantization_method: bnb
top.rope_scaling: none
top.template: default
